version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build:
    # Install node dependencies and run tests
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install typescript -g
      - run:
          command: npm test
          name: Run tests        
      - run:
          command: tsc
          name: Build Library